### ISSUE TITLE
Stop executing queries automatically onclick of event explorer.

### ISSUE THREAD

**Issue by RameshByndoor** [rakam-io/rakam#105]
event explorer queries are executed automatically onclick, with a environment contains too many collections this would add delay before user selects desired events.

**Comment by buremba** [comment]
The default query needs to go through the statistics endpoint which uses materialized view. I agree that the UX is not great if the user wants to select a few collections but let's do the optimization for materialized view (concurrent INSERT) and restrict the number of collections to 20 and group the others as `Others` and see how to UX is. I would rather try to make it work since it's more interactive.
