### ISSUE TITLE
Failed to running docker image

### ISSUE THREAD

**Issue by kerwin** [rakam-io/rakam#21]
Hi,

Can't run rakam with docker image, I got this error message.

```
root@vm~# docker run  -p 9998:9999 buremba/rakam
Starting PostgreSQL 9.4 database server: main.
Error: Could not find or load main class org.rakam.ServiceStarter
```

**Comment by buremba** [comment]
It should be fixed in master branch, could you please try to run the command again?

**Comment by kerwin** [comment]
It's worked, thanks!

I could not find much documentation from http://getrakam.com/, I am leverage an opensource analytics tool / service to do mobile data analytics, What is the stage of current project?

**Comment by buremba** [comment]
Currently, it's used for a few e-commerce websites that need advanced analytics features. Rakam is more like a data warehouse + BI solution, you need to configure it to teach what to track, setup the tracker and write / parameterize SQL queries to create custom reports. If you need basic metrics (counter for visits, page, etc) then I think using Rakam won't make much difference but if you want to roll your custom analytics service then it makes real sense.

The documentation is here: https://rakam.io/doc/ We also have API documentation (https://api.rakam.io/) and configuration manual (https://rakam.io/config). I admit that documentation is still not enough but we're working on it. Currently there is only Javascript tracker so we also need to develop Android & IOS tracker for Rakam. Since we're using RESTFul services already did initial tracker implementation with JS, I don't think that it's a challenge to develop mobile trackers. If you're willing to help, I would be more than happy to collaborate.

Also if you have any questions, feel free to ask. Have a nice day!

**Comment by kerwin** [comment]
Great, thanks @buremba !

I'll check the api documentation and Javascript tracker and see what I can do for mobile trackers.
