### ISSUE TITLE
How to connect from Rakam BI to Rakam API?

### ISSUE THREAD

**Issue by sreekanthpulagam** [rakam-io/rakam#34]

**Comment by buremba** [comment]
Rakam BI is a different product that depends on Rakam API. You can install Rakam API on your servers and use the API by yourself or use Rakam BI to connect to your Rakam API in order to create dashboards but unfortunately Rakam BI is not open-source. Luckily, Rakam BI doesn't actually have access to your Rakam API and works as a web application. When you execute a query on your Rakam API using Rakam BI, your browser sends a request to your Rakam API and doesn't actually send information to app.rakam.io.

If you can share your use-case, it would help me to suggest you the best solution that I can provide.

**Comment by sreekanthpulagam** [comment]
Usecase is 

```
Collect data using client libraries.
Store data in a data warehouse to analyze it later  (Postgresql)
Analyze users with integrated CRM tool.
Visualize data using web application of Rakam similar to BI tools.
```

First 2 are done, I have to analyze using crm & visulize data
which tools will you suggest to crm and BI?
 I can use this happ.rakam.io  for BI but it is not connecting to my out rakam api server

**Comment by buremba** [comment]
You should be able to create a project using this page: http://app.rakam.io/project/create
If still you can't create a project, could you please share the error message?

**Comment by buremba** [comment]
I'm closing this issue since this is not directly related with this repository. Feel free to create a new issue if you see any error.
