### ISSUE TITLE
what is the limit of a Digitalocean instance? 

### ISSUE THREAD

**Issue by davidmann4** [rakam-io/rakam#55]
What is the limit for the docker solution? can it handle 200k actions / month for 2 years?

**Comment by buremba** [comment]
$20 droplet can easily handle 1m actions / month. The only limitation is that since Rakam will work on a single droplet, we won't be provide highly available API and reliable data store. All the data you save will be in a single droplet and if you lose that storage, your data will be gone.

You should also use `docker-compose` and separate the Postgresql and API containers.
