### ISSUE TITLE
Custom Connector Field Does Not Retain Saved Values

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#68]
1. Noticed that if i had saved the funnel with custom connector fields and when i came back, the custom connector shows unchecked but the query is actually getting fired with earlier selected / saved custom connector field. Its confusing. This is a bug. In the back ground it will be firing with custom connector field based group by where as user will be thinking its user based group by. 

2. Can we rename the label of custom connector to "Funnel By".  The text box which shows list of fields should be based on previous JIRA where we can define which columns we want to make it available for Funnel by and which we dont. This should be configurable in custom json to skip the fields to show.

**Comment by buremba** [comment]
1. I will fix the bug today and let you know.
2. We talked about this issue and i think that `funnel by` can be confusing since it can be confused with `group by`. How about `actor fields`?

**Comment by buremba** [comment]
One more issue reported in Slack channel: There is no way to update / delete existing funnel / retention.

**Comment by sambitdixit** [comment]
One more issue reported in Slack channel: There is no way to update / delete existing funnel / retention

Yes this is another bug which does not allow to change an existing saved funnel and resave it. If i want to delete an existing funnel, i dont have a choice.

**Comment by buremba** [comment]
1. Fixed.
2. I renamed it to `custom actor fields`
3. You can delete the funnel via three dots icon -> delete. I prefer to keep it simple and not add modify funnel feature because it's not hard to delete and re-create the funnel and in the future, we may add some precomputation feature and it would make modifying funnels hard or impossible. Let me know if you're not comfortable with this approach.
