### ISSUE TITLE
Ability to show funnels by date range group by day, hour. 

### ISSUE THREAD

**Issue by sambitdixit** [rakam-io/rakam#71]
As an analysts, i created a funnel by selecting the collection, related fields and date range from date picker. Once the base funnel is created i want to group by dimensions like OS, Platform etc and then further see the distribution by day, hour.

**Comment by rajivonat** [comment]
@kazim-i 

We want the same functionality as "Segment->Time Period" that is available in Event explorer analysis in funnel. So requirements are:
a) Currently in funnel I cannot see the distribution of the funnel by day, hour, week etc.., We need to and this and support group by on these time buckets
b) We need to support multiple group by, e.g. I create a funnel group by "Mobile Platform" and then also see the distribution by different time  buckets of day, hour, week, month

**Comment by kazim-i** [comment]
@rajivonat 
It is possible to get the data as in the event explorer, but we can't display it as in the event explorer by nature. Unlike event explorer, funnel has multiple steps. Grouping by fields, time and funnel steps makes it 3 dimensional.

What we can propose is, let's say user started funneling and group by connection_type:
<img width="1051" alt="screen shot 2017-10-25 at 11 54 22 pm" src="https://user-images.githubusercontent.com/32448347/32045653-7d9b690e-ba49-11e7-9bfd-402952bce447.png">
Then, they want to see further detail, here for example, in this image let's say they selected cable dsl
<img width="1217" alt="screen shot 2017-10-25 at 11 55 25 pm" src="https://user-images.githubusercontent.com/32448347/32045761-c2268ab8-ba49-11e7-917c-4e8072e83d95.png">
Here we can create another funnel by filtering with the selected column and make another funnel, easing the process. Afterwards, since here time is not yet implemented, it is grouped by _region. But we can add grouping by time periods along with the fields there.

It is the same functionality, but this approach directs the user to the field of interest. User can repeat the process for all the fields they are interested in. 

The same Please let me know if any further clarificaion needed.

**Comment by rajivonat** [comment]
Can you show a mock up how time bucketing is done on these funnels?

**Comment by kazim-i** [comment]
Hi Rajiv, I have done simple image editing, will try to explain step by step with a screenshot for each step.

Here in the first photo, user already made a simple funnel, they click group by to see the grouping on events by the returning_session property.
![funnel_step1](https://user-images.githubusercontent.com/32448347/32188913-309aee4e-bdba-11e7-9bac-b33abbcdc491.png)

They got the results in this second photo, in order to make further analysis on events that are not returnin_session they click false.
![funnel_step1 5](https://user-images.githubusercontent.com/32448347/32189111-d5ca1c1e-bdba-11e7-853b-0b4834491df9.png)

Here the funnel gets repeated but this time sees the result filtered by false for the field returnin_session. In this subset they want to group by time.
![funnel_step2](https://user-images.githubusercontent.com/32448347/32189220-333af2f6-bdbb-11e7-9894-ef687bb07f2f.png)
A small time selector like this will be opened.
![time_selection](https://user-images.githubusercontent.com/32448347/32189249-4485718a-bdbb-11e7-9e41-2cbbe343992b.png)

Assume they selected hour and the results are grouped in 2017-10-11 06:00:00.000000 and 2017-10-11 07:00:00.000000 , the result set user will see:
![funnel_step3_2](https://user-images.githubusercontent.com/32448347/32189310-76212a18-bdbb-11e7-8d62-6ec4f34debc8.png)

**Comment by buremba** [comment]
The feature is implemented.

**Comment by saloni2409** [comment]
![image](https://user-images.githubusercontent.com/11413225/33174826-9520613c-d07f-11e7-991e-09a2171fe54b.png)

Group by time isnt working

**Comment by saloni2409** [comment]
Bug with group by time:
![image](https://user-images.githubusercontent.com/11413225/33261495-ef7cbd2c-d388-11e7-92aa-598e63a82761.png)

Steps to recreate the issue: 
Group by time column and select any of the time options and query.
Now group by any other non-time column and try querying.

**Comment by buremba** [comment]
Thanks for the bug report @saloni2409 , I fixed it in master.
