### ISSUE TITLE
Download functionality not working.

### ISSUE THREAD

**Issue by saloni2409** [rakam-io/rakam#81]
Download functionality does not download all the data on the page.

**Comment by buremba** [comment]
What's the exact issue? Does it download part of the data or doesn't it work at all?

**Comment by saloni2409** [comment]
It downloads only a few rows.

**Comment by buremba** [comment]
Hey @saloni2409, I couldn't reproduce the bug. Could you please share an example or list the procedures to reproduce the bug? Do you try to download the data in reports page, funnels or event explorer page?

**Comment by sjmach** [comment]
I tried downloading some 1000 rows recently and it worked. @saloni2409  there was an issue some time back on Rakam UI app and it was fixed. Can you please try again?

**Comment by buremba** [comment]
Hey @saloni2409 , it may be related with the browser. I'm closing this issue since this is inactive but feel free to reopen it if the bug occurs again.

**Comment by saloni2409** [comment]
Able to replicate the issue again. Please check snapshots below:

![image](https://user-images.githubusercontent.com/11413225/33755778-61441df0-dc18-11e7-9863-1b48842e2a57.png)

Due to multiple Imeis Ui groups it as "others" which is good for UI. But at the time of download its should download the entire data.

![image](https://user-images.githubusercontent.com/11413225/33755878-e0017e1c-dc18-11e7-8c71-ecf3f3a10cd0.png)

**Comment by buremba** [comment]
This is actually expected behaviour. The event explorer feature is built for easily exploring the event counts so it runs the query in backend with that grouping feature and visualize the final result. The download function is only able to export the data shown in table, since the data is returned as `Others`, there is no way for it to export the full data. You can still download it using the report playground though.
